services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  etl:
    build:
      context: ./backend/etl
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      OMDB_API_KEY: "7253879"  #  Get from your host environment
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    restart: always
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      NODE_ENV: "development"
      PORT: "3001"
    restart: always
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8085:80"  #  Map host port 8080 to container port 80 (nginx default)
    depends_on:
      - api
    environment:
      - VITE_BACKEND_URL=http://localhost:3001

volumes:
  postgres_data: